include:
- ./func/*
kind: ArchiveUploadSpec
name: func-nkiP

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: comp-fn-2e856f78-e317-4310-8fe9-a28ff115fd8d
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: complement-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-nkiP
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-13T19:51:54Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: comp-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: complement-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.complementary_data
    packageref:
      name: comp-fn-2e856f78-e317-4310-8fe9-a28ff115fd8d
      namespace: default
  requestsPerPod: 1
  resources: {}
