include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-lLfU

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onb-br-complement-fn-2a2623f4-72f6-44f9-b1ae-450820a5466b
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-lLfU
  environment:
    name: onb-br-complement-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-05T15:53:14Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onb-br-complement-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 500
  environment:
    name: onb-br-complement-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: onb-br-complement-fn-2a2623f4-72f6-44f9-b1ae-450820a5466b
      namespace: default
  requestsPerPod: 10000
  resources:
    requests:
      cpu: 128m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi
